version: '38'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: ${MYSQL_PASSWORD:-valetbike}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-valetbike}
      MYSQL_DATABASE: valetbike_development
    restart: unless-stopped

  valetbike:
    build: . 
    image: valetbike:latest
    container_name: valetbike
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME:-valetbike}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-valetbike}
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysqldata:
    driver: local
